# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: indicator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0findicator.proto\x12\tindicator\"\\\n\x04OHLC\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"\x99\x01\n\x10IndicatorRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07periods\x18\x02 \x03(\x05\x12\x37\n\x06params\x18\x03 \x03(\x0b\x32\'.indicator.IndicatorRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf0\x01\n\x10\x43\x61lculateRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x1d\n\x04ohlc\x18\x03 \x03(\x0b\x32\x0f.indicator.OHLC\x12/\n\nindicators\x18\x04 \x03(\x0b\x32\x1b.indicator.IndicatorRequest\x12\x39\n\x07options\x18\x05 \x03(\x0b\x32(.indicator.CalculateRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x0fIndicatorResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\x05\x12\x0e\n\x06values\x18\x03 \x03(\x01\x12\x12\n\ntimestamps\x18\x04 \x03(\x03\"@\n\x11\x43\x61lculateResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.indicator.IndicatorResult2Z\n\x10IndicatorService\x12\x46\n\tCalculate\x12\x1b.indicator.CalculateRequest\x1a\x1c.indicator.CalculateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDICATORREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_INDICATORREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CALCULATEREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_CALCULATEREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_OHLC']._serialized_start=30
  _globals['_OHLC']._serialized_end=122
  _globals['_INDICATORREQUEST']._serialized_start=125
  _globals['_INDICATORREQUEST']._serialized_end=278
  _globals['_INDICATORREQUEST_PARAMSENTRY']._serialized_start=233
  _globals['_INDICATORREQUEST_PARAMSENTRY']._serialized_end=278
  _globals['_CALCULATEREQUEST']._serialized_start=281
  _globals['_CALCULATEREQUEST']._serialized_end=521
  _globals['_CALCULATEREQUEST_OPTIONSENTRY']._serialized_start=475
  _globals['_CALCULATEREQUEST_OPTIONSENTRY']._serialized_end=521
  _globals['_INDICATORRESULT']._serialized_start=523
  _globals['_INDICATORRESULT']._serialized_end=606
  _globals['_CALCULATERESPONSE']._serialized_start=608
  _globals['_CALCULATERESPONSE']._serialized_end=672
  _globals['_INDICATORSERVICE']._serialized_start=674
  _globals['_INDICATORSERVICE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
