"""
GAS Telegram Bot Integration API
- POST /telegram/link     — user links their Telegram account to GAS (authenticated)
- GET  /telegram/me       — check link status
- POST /bot/analyze       — legacy endpoint (all flows, same pipeline)
- POST /bot/signal        — Signal flow: indicator + strategy-core signal + calendar warning
- POST /bot/analysis      — Analisa flow: strategy-core technical + calendar + correlation
- POST /bot/analyst       — Analyst flow: strategy-core hybrid + fundamental + backtest summary
"""
from fastapi import APIRouter, Depends, HTTPException, Header, Request
from pydantic import BaseModel
from typing import Optional, List
import os
import asyncio
import redis.asyncio as aioredis
import httpx

from ...core.dependencies import get_current_user_info
from .billing import deduct_credits, get_user_credits
from .analysis import STYLE_MATRIX, STRATEGY_CORE_URL, KIMI_API_KEY, KIMI_BASE_URL, KIMI_MODEL

router = APIRouter(tags=["Telegram Bot"])

REDIS_URL = os.getenv("REDIS_URL", "redis://gas-redis:6379/0")
BOT_API_KEY = os.getenv("BOT_API_KEY", "gas-bot-key-2026-secret")

_redis = None


async def _get_redis() -> aioredis.Redis:
    global _redis
    if _redis is None:
        _redis = aioredis.from_url(REDIS_URL, decode_responses=True)
    return _redis


def _verify_bot_key(x_bot_key: Optional[str] = Header(None)):
    if x_bot_key != BOT_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid bot API key")
    return True


# ── User: link Telegram account ───────────────────────────────────────────

class LinkRequest(BaseModel):
    code: str  # 8-char code generated by bot


@router.post("/telegram/link")
async def link_telegram(body: LinkRequest, user_info: dict = Depends(get_current_user_info)):
    """
    Authenticated user submits the link code from the Telegram bot.
    Links their Telegram ID to their GAS account in Redis.
    """
    r = await _get_redis()
    tg_user_id = await r.get(f"tg:link:{body.code}")
    if not tg_user_id:
        raise HTTPException(status_code=400, detail="Kode tidak valid atau sudah kedaluwarsa (15 menit)")

    gas_user_id = user_info["user_id"]
    # Store permanent binding
    await r.set(f"tg:bind:{tg_user_id}", gas_user_id)
    # Remove the one-time link code
    await r.delete(f"tg:link:{body.code}")

    return {
        "ok": True,
        "message": "Akun Telegram berhasil dihubungkan ke GAS!",
        "tg_user_id": tg_user_id,
        "gas_user_id": gas_user_id,
    }


@router.get("/telegram/me")
async def telegram_link_status(user_info: dict = Depends(get_current_user_info)):
    """Check if the current user has a linked Telegram account."""
    r = await _get_redis()
    gas_user_id = user_info["user_id"]
    # Search for any tg:bind that maps to this gas_user_id
    # We store tg:bind:{tg_id} = gas_user_id, so scan for the value
    # For efficiency, also store reverse: tg:gas:{gas_user_id} = tg_user_id
    tg_user_id = await r.get(f"tg:gas:{gas_user_id}")
    return {
        "linked": tg_user_id is not None,
        "tg_user_id": tg_user_id,
    }


@router.delete("/telegram/unlink")
async def unlink_telegram(user_info: dict = Depends(get_current_user_info)):
    """Unlink Telegram from this GAS account."""
    r = await _get_redis()
    gas_user_id = user_info["user_id"]
    tg_user_id = await r.get(f"tg:gas:{gas_user_id}")
    if tg_user_id:
        await r.delete(f"tg:bind:{tg_user_id}")
        await r.delete(f"tg:gas:{gas_user_id}")
    return {"ok": True, "message": "Akun Telegram berhasil dilepas."}


# ── Bot: internal analyze endpoint ────────────────────────────────────────

class BotAnalyzeRequest(BaseModel):
    gas_user_id: str
    pair: str
    style: str          # scalping / intraday / swing
    feature: str = "technical"


STRATEGY_CORE_BOT_URL   = os.getenv("STRATEGY_CORE_URL",          "http://gas-strategy-core:7003")
CALENDAR_NEWS_URL       = os.getenv("CALENDAR_NEWS_URL",          "http://gas-calendar-news-service:9601")
FUNDAMENTAL_DATA_URL    = os.getenv("FUNDAMENTAL_DATA_URL",       "http://gas-fundamental-data-service:9603")
TREND_ENGINE_URL        = os.getenv("TREND_ENGINE_URL",           "http://gas-trend-engine:9513")
MARKET_PHASE_URL        = os.getenv("MARKET_PHASE_URL",           "http://gas-market-phase:9510")

# Credit cost per trading style (matches bot's STYLE_COST)
_STYLE_COST = {"scalping": 2, "intraday": 3, "swing": 4, "position": 5}

# Style → primary timeframe
_STYLE_TF = {"scalping": "M15", "intraday": "H1", "swing": "H4", "position": "D1"}

# Plan → model_tier mapping (strategy-core uses model_tier, not plan)
_PLAN_TIER = {
    "ultra":     "ultra",
    "ultimate":  "ultra",
    "premium":   "pro",
    "plus":      "advanced",
    "essential": "basic",
    "trial":     "basic",
    "free":      "basic",
}


@router.post("/bot/analyze")
async def bot_analyze(
    body: BotAnalyzeRequest,
    authorized: bool = Depends(_verify_bot_key),
):
    """
    Called by gas-telegram-bot to run AI analysis for a linked user.
    Routes to gas-strategy-core for real AI signal generation.
    All plans allowed; plan tier determines AI model quality.
    """
    r = await _get_redis()

    # Read plan (all plans allowed — quality varies by tier)
    plan = await r.get(f"user:{body.gas_user_id}:plan") or "free"

    # Credit cost varies by style
    cost = _STYLE_COST.get(body.style.lower(), 3)
    # Free/trial users pay 1 credit
    if plan in ("free", "trial"):
        cost = 1

    ok, remaining = await deduct_credits(body.gas_user_id, cost, is_admin=False)
    if not ok:
        raise HTTPException(402, detail=f"Kredit tidak cukup. Sisa: {remaining}")

    timeframe = _STYLE_TF.get(body.style.lower(), "H1")

    model_tier = _PLAN_TIER.get(plan.lower(), "basic")

    # Call gas-strategy-core for real AI signal
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{STRATEGY_CORE_BOT_URL}/v1/analysis/signal",
                json={
                    "pair": body.pair.upper(),
                    "timeframe": timeframe,
                    "style": body.style.lower(),
                    "model_tier": model_tier,
                    "user_id": body.gas_user_id,
                },
            )
            resp.raise_for_status()
            result = resp.json()
    except Exception as e:
        raise HTTPException(503, detail=f"AI engine error: {str(e)[:100]}")

    # Normalise response to match bot formatter expectations
    return {
        "pair": body.pair,
        "style": body.style,
        "grade": result.get("grade", "B"),
        "stars": result.get("stars", 2),
        "probability": result.get("probability", result.get("confidence", 55)),
        "signal": result.get("signal", result.get("direction", "WAIT")),
        "bias": result.get("bias", "Neutral"),
        "entry": result.get("entry", result.get("entry_zone")),
        "stop_loss": result.get("sl", result.get("stop_loss")),
        "tp1": result.get("tp1", result.get("take_profit_1")),
        "tp2": result.get("tp2", result.get("take_profit_2")),
        "tp3": result.get("tp3", result.get("take_profit_3")),
        "rr": result.get("rr", result.get("risk_reward", "1:2")),
        "summary": result.get("summary", result.get("reasoning", "")),
        "session": result.get("session", ""),
        "credits_used": cost,
        "credits_remaining": remaining,
        "source": result.get("source", "ai"),
        "model": result.get("model", ""),
    }


# ── Shared helpers for new bot endpoints ─────────────────────────────────

async def _core_post(endpoint: str, payload: dict, timeout: int = 45) -> dict:
    """Fire-and-forget POST to strategy-core; returns {} on error."""
    try:
        async with httpx.AsyncClient(timeout=timeout) as c:
            r = await c.post(f"{STRATEGY_CORE_BOT_URL}{endpoint}", json=payload)
            r.raise_for_status()
            return r.json()
    except Exception:
        return {}


async def _svc_get(base_url: str, path: str, params: dict = None, timeout: int = 10) -> dict:
    """Fire-and-forget GET to a microservice; returns {} on error."""
    try:
        async with httpx.AsyncClient(timeout=timeout) as c:
            r = await c.get(f"{base_url}{path}", params=params or {})
            r.raise_for_status()
            return r.json()
    except Exception:
        return {}


async def _svc_post(base_url: str, path: str, payload: dict, timeout: int = 15) -> dict:
    """Fire-and-forget POST to a microservice; returns {} on error."""
    try:
        async with httpx.AsyncClient(timeout=timeout) as c:
            r = await c.post(f"{base_url}{path}", json=payload)
            r.raise_for_status()
            return r.json()
    except Exception:
        return {}


def _resolve_tf(style: str) -> str:
    return {"scalping": "M15", "intraday": "H1", "swing": "H4", "position": "D1"}.get(style.lower(), "H1")


def _style_tfs(style: str) -> list:
    return STYLE_MATRIX.get(style.lower(), {}).get("tfs", ["H1"])


# ── NEW: /bot/signal ──────────────────────────────────────────────────────────

class BotFlowRequest(BaseModel):
    gas_user_id: str
    pair: str
    style: str
    ai_tier: str = "basic"


@router.post("/bot/signal")
async def bot_signal(
    body: BotFlowRequest,
    authorized: bool = Depends(_verify_bot_key),
):
    """
    Signal flow — fast entry signal.
    Pipeline: strategy-core /signal + calendar-news high-impact check.
    Returns: standard signal card + calendar_warning field.
    """
    r = await _get_redis()
    plan = await r.get(f"user:{body.gas_user_id}:plan") or "free"
    cost = _STYLE_COST.get(body.style.lower(), 3)
    if plan in ("free", "trial"):
        cost = 1

    ok, remaining = await deduct_credits(body.gas_user_id, cost, is_admin=False)
    if not ok:
        raise HTTPException(402, detail=f"Kredit tidak cukup. Sisa: {remaining}")

    tf       = _resolve_tf(body.style)
    tf_mtx   = _style_tfs(body.style)
    tier     = _PLAN_TIER.get(plan.lower(), "basic")

    # Run signal + calendar in parallel
    signal_task  = _core_post("/v1/analysis/signal", {
        "pair": body.pair.upper(), "timeframe": tf,
        "style": body.style.lower(), "timeframe_matrix": tf_mtx,
        "model_tier": tier, "user_id": body.gas_user_id,
    }, timeout=45)
    calendar_task = _svc_get(CALENDAR_NEWS_URL, "/calendar", {"limit": 5})

    signal_data, cal_data = await asyncio.gather(signal_task, calendar_task)

    if not signal_data:
        raise HTTPException(503, detail="Signal engine unavailable")

    # Extract calendar warning for high-impact events
    events      = cal_data.get("events", []) if cal_data else []
    hi_events   = [e for e in events if str(e.get("impact", "")).lower() == "high"]
    cal_warning = ""
    if hi_events:
        titles = ", ".join(e.get("title", e.get("event", "?"))[:30] for e in hi_events[:2])
        cal_warning = f"⚠️ {len(hi_events)} high-impact event hari ini: {titles}"

    return {
        "pair":              body.pair.upper(),
        "style":             body.style,
        "pipeline":          "signal",
        "grade":             signal_data.get("grade", "B"),
        "stars":             signal_data.get("stars", 2),
        "probability":       signal_data.get("probability", signal_data.get("confidence", 55)),
        "signal":            signal_data.get("signal", signal_data.get("direction", "WAIT")),
        "bias":              signal_data.get("bias", "Neutral"),
        "entry":             signal_data.get("entry", signal_data.get("entry_zone")),
        "stop_loss":         signal_data.get("sl", signal_data.get("stop_loss")),
        "tp1":               signal_data.get("tp1"),
        "tp2":               signal_data.get("tp2"),
        "tp3":               signal_data.get("tp3"),
        "rr":                signal_data.get("rr", signal_data.get("risk_reward", "1:2")),
        "summary":           signal_data.get("summary", signal_data.get("reasoning", "")),
        "session":           signal_data.get("session", ""),
        "calendar_warning":  cal_warning,
        "credits_used":      cost,
        "credits_remaining": remaining,
        "model":             signal_data.get("model", ""),
        "source":            signal_data.get("source", "ai"),
    }


# ── NEW: /bot/analysis ────────────────────────────────────────────────────────

@router.post("/bot/analysis")
async def bot_analysis(
    body: BotFlowRequest,
    authorized: bool = Depends(_verify_bot_key),
):
    """
    Analisa flow — deep technical multi-timeframe analysis.
    Pipeline: strategy-core /technical (MTF indicators) + calendar context + correlation.
    Returns: enriched technical card with zones, MTF breakdown, calendar, correlation.
    """
    r = await _get_redis()
    plan = await r.get(f"user:{body.gas_user_id}:plan") or "free"
    cost = max(3, _STYLE_COST.get(body.style.lower(), 3))
    if plan in ("free", "trial"):
        cost = 2

    ok, remaining = await deduct_credits(body.gas_user_id, cost, is_admin=False)
    if not ok:
        raise HTTPException(402, detail=f"Kredit tidak cukup. Sisa: {remaining}")

    tf     = _resolve_tf(body.style)
    tf_mtx = _style_tfs(body.style)
    tier   = _PLAN_TIER.get(plan.lower(), "basic")

    # Run 3 calls in parallel: technical + calendar + correlation
    tech_task  = _core_post("/v1/analysis/technical", {
        "pair": body.pair.upper(), "timeframe": tf,
        "style": body.style.lower(), "timeframe_matrix": tf_mtx,
        "indicators": ["RSI", "MACD", "ADX", "BB", "EMA", "ATR"],
        "model_tier": tier, "user_id": body.gas_user_id,
        "pure_compute": False,
    }, timeout=50)
    cal_task   = _svc_get(CALENDAR_NEWS_URL, "/calendar", {"limit": 8})
    corr_task  = _core_post("/v1/analysis/correlation", {
        "pair": body.pair.upper(), "timeframe": tf,
        "user_id": body.gas_user_id,
    }, timeout=20)

    tech_data, cal_data, corr_data = await asyncio.gather(tech_task, cal_task, corr_task)

    if not tech_data:
        raise HTTPException(503, detail="Analysis engine unavailable")

    # Calendar summary
    events    = cal_data.get("events", []) if cal_data else []
    hi_events = [e for e in events if str(e.get("impact", "")).lower() == "high"]
    cal_ctx   = f"{len(hi_events)} high-impact events today" if hi_events else "No high-impact events today"
    cal_titles = [e.get("title", e.get("event", ""))[:40] for e in hi_events[:3]]

    # Correlation summary
    corr_matrix = corr_data.get("correlation_matrix", {}) if corr_data else {}
    top_corr    = ""
    if isinstance(corr_matrix, dict) and body.pair.upper() in corr_matrix:
        others = {k: v for k, v in corr_matrix[body.pair.upper()].items() if k != body.pair.upper()}
        if others:
            top_k = max(others, key=lambda x: abs(float(others[x])))
            top_corr = f"{top_k} ({others[top_k]:.2f})"

    return {
        "pair":              body.pair.upper(),
        "style":             body.style,
        "pipeline":          "analysis",
        "grade":             tech_data.get("grade", tech_data.get("result", {}).get("grade", "B")),
        "stars":             tech_data.get("stars", 3),
        "probability":       tech_data.get("probability", tech_data.get("confidence", 60)),
        "signal":            tech_data.get("signal", tech_data.get("direction", tech_data.get("bias", "NEUTRAL"))),
        "bias":              tech_data.get("bias", "Neutral"),
        "entry":             tech_data.get("entry", tech_data.get("entry_zone")),
        "stop_loss":         tech_data.get("sl", tech_data.get("stop_loss")),
        "tp1":               tech_data.get("tp1"),
        "tp2":               tech_data.get("tp2"),
        "tp3":               tech_data.get("tp3"),
        "rr":                tech_data.get("rr", tech_data.get("risk_reward", "1:2")),
        "summary":           tech_data.get("summary", tech_data.get("result", {}).get("summary", "")),
        "session":           tech_data.get("session", ""),
        # Enrichment fields
        "timeframe_matrix":  tf_mtx,
        "indicators":        tech_data.get("indicators", {}),
        "mtf_bias":          tech_data.get("mtf_bias", tech_data.get("timeframe_analysis", {})),
        "support_resistance": tech_data.get("support_resistance", tech_data.get("key_levels", {})),
        "calendar_context":  cal_ctx,
        "calendar_events":   cal_titles,
        "top_correlation":   top_corr,
        "model":             tech_data.get("model", ""),
        "credits_used":      cost,
        "credits_remaining": remaining,
        "source":            tech_data.get("source", "ai"),
    }


# ── NEW: /bot/analyst ─────────────────────────────────────────────────────────

@router.post("/bot/analyst")
async def bot_analyst(
    body: BotFlowRequest,
    authorized: bool = Depends(_verify_bot_key),
):
    """
    Analyst flow — full AI research report.
    Pipeline: strategy-core /hybrid + fundamental data + trend-engine + market-phase.
    Returns: comprehensive research card with macro, trend, phase, trading plan.
    """
    r = await _get_redis()
    plan = await r.get(f"user:{body.gas_user_id}:plan") or "free"
    cost = max(5, _STYLE_COST.get(body.style.lower(), 3) + 2)
    if plan in ("free", "trial"):
        cost = 3

    ok, remaining = await deduct_credits(body.gas_user_id, cost, is_admin=False)
    if not ok:
        raise HTTPException(402, detail=f"Kredit tidak cukup. Sisa: {remaining}")

    tf     = _resolve_tf(body.style)
    tf_mtx = _style_tfs(body.style)
    tier   = _PLAN_TIER.get(plan.lower(), "basic")

    # Run 4 calls in parallel: hybrid + fundamental + trend + market-phase
    hybrid_task  = _core_post("/v1/analysis/hybrid", {
        "pair": body.pair.upper(), "timeframe": tf,
        "style": body.style.lower(), "model_tier": tier,
        "user_id": body.gas_user_id,
    }, timeout=60)
    fund_task    = _svc_get(FUNDAMENTAL_DATA_URL, f"/fundamental/{body.pair.upper()}/summary")
    trend_task   = _svc_post(TREND_ENGINE_URL, "/trend", {
        "symbol": body.pair.upper(), "timeframe": tf, "method": "both",
    })
    phase_task   = _svc_post(MARKET_PHASE_URL, "/phase", {
        "symbol": body.pair.upper(), "timeframe": tf,
    })

    hybrid_data, fund_data, trend_data, phase_data = await asyncio.gather(
        hybrid_task, fund_task, trend_task, phase_task
    )

    if not hybrid_data:
        raise HTTPException(503, detail="Analyst engine unavailable")

    # Fundamental summary
    fund_summary = ""
    if fund_data:
        fund_summary = fund_data.get("summary", fund_data.get("ai_summary", ""))
        if not fund_summary:
            fund_summary = str(fund_data.get("data", ""))[:200]

    # Trend direction
    trend_signal   = ""
    trend_strength = ""
    if trend_data:
        trend_signal   = trend_data.get("signal", "")
        trend_strength = f"{trend_data.get('strength', 0):.0%}" if trend_data.get("strength") else ""

    # Market phase
    mkt_phase      = ""
    phase_conf     = ""
    if phase_data:
        mkt_phase  = phase_data.get("phase", "")
        phase_conf = f"{phase_data.get('confidence', 0):.0%}" if phase_data.get("confidence") else ""

    return {
        "pair":              body.pair.upper(),
        "style":             body.style,
        "pipeline":          "analyst",
        "grade":             hybrid_data.get("grade", "A"),
        "stars":             hybrid_data.get("stars", 4),
        "probability":       hybrid_data.get("probability", hybrid_data.get("confidence", 65)),
        "signal":            hybrid_data.get("signal", hybrid_data.get("direction", "NEUTRAL")),
        "bias":              hybrid_data.get("bias", "Neutral"),
        "entry":             hybrid_data.get("entry", hybrid_data.get("entry_zone")),
        "stop_loss":         hybrid_data.get("sl", hybrid_data.get("stop_loss")),
        "tp1":               hybrid_data.get("tp1"),
        "tp2":               hybrid_data.get("tp2"),
        "tp3":               hybrid_data.get("tp3"),
        "rr":                hybrid_data.get("rr", hybrid_data.get("risk_reward", "1:3")),
        "summary":           hybrid_data.get("summary", hybrid_data.get("result", {}).get("summary", "")),
        "session":           hybrid_data.get("session", ""),
        # Enrichment fields
        "fundamental":       fund_summary,
        "trend_direction":   trend_signal,
        "trend_strength":    trend_strength,
        "market_phase":      mkt_phase,
        "phase_confidence":  phase_conf,
        "ai_reasoning":      hybrid_data.get("reasoning", hybrid_data.get("ai_analysis", "")),
        "timeframe_matrix":  tf_mtx,
        "model":             hybrid_data.get("model", ""),
        "credits_used":      cost,
        "credits_remaining": remaining,
        "source":            hybrid_data.get("source", "ai"),
    }


# ── Also store reverse binding when linking ───────────────────────────────
# Patch the link endpoint to also write tg:gas:{gas_user_id} = tg_user_id

@router.post("/telegram/link-v2")
async def link_telegram_v2(body: LinkRequest, user_info: dict = Depends(get_current_user_info)):
    """Same as /link but also stores reverse index."""
    r = await _get_redis()
    tg_user_id = await r.get(f"tg:link:{body.code}")
    if not tg_user_id:
        raise HTTPException(400, detail="Kode tidak valid atau sudah kedaluwarsa")
    gas_user_id = user_info["user_id"]
    await r.set(f"tg:bind:{tg_user_id}", gas_user_id)
    await r.set(f"tg:gas:{gas_user_id}", tg_user_id)
    await r.delete(f"tg:link:{body.code}")
    return {
        "ok": True,
        "message": "Akun Telegram berhasil dihubungkan!",
        "tg_user_id": tg_user_id,
    }
