apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://gas-loki:3100
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://gas-prometheus:9090
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
