version = 5.4.0
archive_dir = /etc/letsencrypt/archive/gasstrategyai.xyz
cert = /etc/letsencrypt/live/gasstrategyai.xyz/cert.pem
privkey = /etc/letsencrypt/live/gasstrategyai.xyz/privkey.pem
chain = /etc/letsencrypt/live/gasstrategyai.xyz/chain.pem
fullchain = /etc/letsencrypt/live/gasstrategyai.xyz/fullchain.pem
[renewalparams]
account = 63309dc6e4c755ab7e83137f9e9a25ee
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
gasstrategyai.xyz = /var/www/certbot
www.gasstrategyai.xyz = /var/www/certbot
admin.gasstrategyai.xyz = /var/www/certbot
api.gasstrategyai.xyz = /var/www/certbot
app.gasstrategyai.xyz = /var/www/certbot
blog.gasstrategyai.xyz = /var/www/certbot
docs.gasstrategyai.xyz = /var/www/certbot
pricing.gasstrategyai.xyz = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-04-09T14:14:54
